# CONSTANTS
SUBJECT = "subject"
PREDICATE = "predicate"
OBJECT = "object"

OP_EQUALS = "="
OP_NOT_EQUALS = "!="

OP_AND = "AND"
OP_OPT = "OPT"
OP_UNION = "UNION"
OP_FILTER = "FILTER"

OP_SQL_AND = "AND"
OP_SQL_OR = "OR"
OP_SQL_IS = " IS"
OP_SQL_NOT = "IS NOT"

SQL_NULL = "null"

LOGICAL_CONNECTIVE_AND = "&&"
LOGICAL_CONNECTIVE_OR = "||"

SQL_INNER_JOIN = "INNER JOIN"
SQL_LEFT_JOIN = "LEFT JOIN"
SQL_LEFT_OUTER_JOIN = "LEFT OUTER JOIN"  # user on UNION

COLOR_FAIL = '\033[91m'
COLOR_OK = '\033[92m'
COLOR_BLUE = '\033[94m'
COLOR_END = '\033[0m'
