insert(":user1", ":firstname", "John")
	insert(":user1", ":surname", "Simmons")
	insert(":user2", ":surname", "Kobe")
	insert(":user2", ":surname", "Bryant")
	insert(":user2", ":plays", ":sport1")
	insert(":user2", ":livesIn", ":location1")
	insert(":user2", ":bornIn", ":location2")
	# sport
	insert(":sport1", ":name", "Basketball")
	insert(":sport1", ":name", "Football")
	insert(":sport1", ":name", "Hockey")
	insert(":sport1", ":name", "Baseball")
	# locations
	insert(":location1", ":name", "Los Angeles")
	insert(":location2", ":name", "Philadelphia")
	insert(":location3", ":name", "Oakland")
	insert(":location4", ":name", "California")
	insert(":location5", ":name", "USA")
	insert(":location6", ":name", "North America")

	insert(":location1", ":location", "Los Angeles")
	insert(":location2", ":location", "Philadelphia")
	insert(":location3", ":location", "Oakland")
	insert(":location4", ":location", "California")
	insert(":location5", ":location", "USA")
	insert(":location6", ":location", "North America")

	insert(":location1", ":isLocatedIn", ":location4")
	insert(":location3", ":isLocatedIn", ":location4")
	insert(":location4", ":isLocatedIn", ":location5")
	insert(":location5", ":isLocatedIn", ":location6")